CREATE TABLE IF NOT EXISTS tm_user (
  id BIGINT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  nickname VARCHAR(64) NOT NULL,
  phone VARCHAR(32) NULL,
  email VARCHAR(128) NULL,
  avatar_url VARCHAR(512) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_user_preference (
  id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  budget_level VARCHAR(32) NULL,
  travel_style VARCHAR(64) NULL,
  preferred_city VARCHAR(128) NULL,
  preferred_tags VARCHAR(255) NULL,
  transportation VARCHAR(64) NULL,
  hotel_level VARCHAR(64) NULL,
  diet_preference VARCHAR(128) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_preference_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_city (
  id BIGINT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  province VARCHAR(64) NULL,
  country VARCHAR(64) NOT NULL DEFAULT 'China',
  description VARCHAR(1000) NULL,
  cover_image VARCHAR(512) NULL,
  popularity INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_city_keyword (name, province)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_travel_tag (
  id BIGINT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  category VARCHAR(64) NOT NULL,
  color VARCHAR(32) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_tag_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_attraction (
  id BIGINT PRIMARY KEY,
  city_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL,
  address VARCHAR(255) NULL,
  description VARCHAR(1000) NULL,
  rating DECIMAL(3,1) NOT NULL DEFAULT 0.0,
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  tags VARCHAR(255) NULL,
  opening_hours VARCHAR(128) NULL,
  image_url VARCHAR(512) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_attraction_city (city_id),
  INDEX idx_attraction_filter (category, rating)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_hotel (
  id BIGINT PRIMARY KEY,
  city_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT 'hotel',
  address VARCHAR(255) NULL,
  description VARCHAR(1000) NULL,
  rating DECIMAL(3,1) NOT NULL DEFAULT 0.0,
  price_range VARCHAR(64) NULL,
  tags VARCHAR(255) NULL,
  image_url VARCHAR(512) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_hotel_city (city_id),
  INDEX idx_hotel_filter (category, rating)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_restaurant (
  id BIGINT PRIMARY KEY,
  city_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT 'restaurant',
  cuisine VARCHAR(64) NULL,
  address VARCHAR(255) NULL,
  description VARCHAR(1000) NULL,
  rating DECIMAL(3,1) NOT NULL DEFAULT 0.0,
  average_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  tags VARCHAR(255) NULL,
  image_url VARCHAR(512) NULL,
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_restaurant_city (city_id),
  INDEX idx_restaurant_filter (category, rating)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_favorite (
  id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id BIGINT NOT NULL,
  note VARCHAR(255) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_favorite_target (user_id, target_type, target_id, deleted),
  INDEX idx_favorite_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_travel_note (
  id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  city_id BIGINT NULL,
  attraction_id BIGINT NULL,
  title VARCHAR(128) NOT NULL,
  content TEXT NOT NULL,
  visibility VARCHAR(32) NOT NULL DEFAULT 'private',
  status TINYINT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_note_user (user_id),
  INDEX idx_note_attraction (attraction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_trip_plan (
  id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(128) NOT NULL,
  destination_city VARCHAR(128) NOT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  travel_days INT NOT NULL DEFAULT 1,
  budget DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  status VARCHAR(32) NOT NULL DEFAULT 'draft',
  summary VARCHAR(1000) NULL,
  raw_plan_json JSON NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_trip_user (user_id),
  INDEX idx_trip_city (destination_city)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_trip_day (
  id BIGINT PRIMARY KEY,
  trip_plan_id BIGINT NOT NULL,
  day_no INT NOT NULL,
  date DATE NULL,
  title VARCHAR(128) NULL,
  summary VARCHAR(1000) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_trip_day_plan (trip_plan_id, day_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_trip_item (
  id BIGINT PRIMARY KEY,
  trip_day_id BIGINT NOT NULL,
  item_order INT NOT NULL DEFAULT 1,
  item_type VARCHAR(32) NOT NULL,
  title VARCHAR(128) NOT NULL,
  location VARCHAR(255) NULL,
  start_time VARCHAR(32) NULL,
  end_time VARCHAR(32) NULL,
  cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  note VARCHAR(1000) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_trip_item_day (trip_day_id, item_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tm_ai_analysis_record (
  id BIGINT PRIMARY KEY,
  user_id BIGINT NULL,
  analysis_type VARCHAR(64) NOT NULL,
  target_type VARCHAR(64) NULL,
  target_id BIGINT NULL,
  request_summary VARCHAR(1000) NULL,
  result_summary VARCHAR(1000) NULL,
  result_json JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'success',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_ai_record_type (analysis_type),
  INDEX idx_ai_record_target (target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
