<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.zkry</groupId>
        <artifactId>travel-mind</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>common</artifactId>
    <packaging>pom</packaging>


    <description>
        common 公用模块
    </description>
    <modules>
        <module>core</module>
        <module>json</module>
        <module>web</module>
        <module>mybatis</module>
        <module>satoken</module>
        <module>redis</module>
    </modules>
</project>
